CREATE TABLE item (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  genre VARCHAR(100),
  author VARCHAR(100),
  source VARCHAR(100),
  label VARCHAR(100),
  book_id INT,
  game_id INT,
  author_id INT,
  FOREIGN KEY (book_id) REFERENCES book (id)
  album_id INT,
  FOREIGN KEY (book_id) REFERENCES book (id),
  FOREIGN KEY (album_id) REFERENCES music_album(id)
);

CREATE TABLE book (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  publisher VARCHAR(255) NOT NULL,
  cover_state VARCHAR(25) NOT NULL,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  item_id INT NOT NULL
);

CREATE TABLE label (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  color VARCHAR(100) NOT NULL,
  archived BOOLEAN NOT NULL,
  book_id INT NOT NULL,
  item_id INT NOT NULL
);

CREATE TABLE movie (
    id INT GENERATED ALWAYS AS IDENTITY,
    published_date DATE,
    name VARCHAR(100),
    silent BOOLEAN,
    FOREIGN KEY(id) REFERENCES items(id)
);

CREATE TABLE source (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  source_name VARCHAR(80)
);
CREATE TABLE author (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  archived BOOLEAN NOT NULL,
  item_id INT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES author (id),
  FOREIGN KEY (author_id) REFERENCES game (id),
);
CREATE TABLE game (
  multiplayer BOOLEAN NOT NULL,
  last_played_at DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  item_id INT NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game (id)
);


ALTER TABLE book ADD FOREIGN KEY (item_id) REFERENCES item (id);
ALTER TABLE label ADD FOREIGN KEY (item_id) REFERENCES item (id);
ALTER TABLE label ADD FOREIGN KEY (book_id) REFERENCES book (id);

CREATE TABLE music_album (
    id SERIAL PRIMARY KEY,
    artist VARCHAR(100),
    title VARCHAR(100),
    publish_date DATE NOT NULL,
    on_spotify BOOLEAN DEFAULT FALSE,
    genre VARCHAR(100)
);

CREATE TABLE genre (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    items VARCHAR(100)
);
